[versions]
jackson = "2.16.1"
mockk = "1.13.5"
fixture = "1.2.0"
jwt = "0.12.3"
redisson = "3.52.0"
springdoc = "2.8.4"
mapstruct = "1.6.2"
lombok = "1.18.42"
transactional = "6.1.0"

[libraries]

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

jwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jwt" }
jwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jwt" }
jwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jwt" }

mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

org-redisson-starter = {module = "org.redisson:redisson-spring-boot-starter", version.ref = "redisson"}


spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-web-flux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-logging = { module = "org.springframework.boot:spring-boot-starter-logging" }
spring-boot-starter-kafka = { module = "org.springframework.kafka:spring-kafka" }
spring-boot-starter-transactional = { module = "org.springframework:spring-tx", version.ref = "transactional" }
spring-boot-spring-doc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }



spring-context = { module = "org.springframework:spring-context" }
spring-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

test-fixture = { module = "com.appmattus.fixture:fixture", version.ref = "fixture" }

[bundles]
jackson = [
    "jackson-databind",
    "jackson-datatype-jsr310",
]
jwt = [
    "jwt-api",
    "jwt-impl",
    "jwt-jackson"
]
bootstrap = [
    "spring-boot-starter-validation",
    "jackson-datatype-jsr310",
]
test = [
    "test-fixture",
]
